Add support to compile for Scala 2.12
Currently uses 2.12.0-M4 because ScalaTest doesn't exist yet for M5. Asides from that,
almost all the subprojects have been disabled (the integration ones) because they too are
lacking 2.12.x support.

Another interesting note is that with the following version of Java:

java version "1.8.0_05"
Java(TM) SE Runtime Environment (build 1.8.0_05-b13)

I got a strange error when the compiler-interface was getting compiled:

[info] 'compiler-interface' not yet compiled for Scala 2.12.0-M4. Compiling...
java.lang.VerifyError: Uninitialized object exists on backward branch 209
Exception Details:
  Location:
    scala/collection/immutable/HashMap$HashTrieMap.split()Lscala/collection/immutable/Seq; @249: goto
  Reason:
    Error exists in the bytecode

Upgrading to 1.8.0_101 fixed it and I was able to run the tests.